### ISSUE TITLE
Not even possible to start 

### ISSUE THREAD

**Issue by montella1507** [blacksonic/angular2-aot-webpack#10]
Hello i have downloaded your repo, run npm install and try to start the solution with npm run start:

There are like 100 errors like:
ERROR in [default]
Cannot find type definition file for 'es6-shim'.

ERROR in [default]
Cannot find type definition file for 'node'.

ERROR in [default] C:\test aot\angular2-aot-webpack-master\app\hello-world.component.ts:5:12
Cannot find name 'require'.

ERROR in [default] C:\test aot\angular2-aot-webpack-master\node_modules\@angular\common\src\directives\ng_class.d.ts:46:33
Cannot find name 'Set'.

ERROR in [default] C:\test aot\angular2-aot-webpack-master\node_modules\@angular\common\src\pipes\async_pipe.d.ts:39:37 
Cannot find name 'Promise'.

**Comment by sonicoder86** [comment]
Typescript can not find the typings, although they are installed through `@types/node` and `@types/es6-shim`.
It can be connected to Typescript - Windows, because it works on Linux after a clean install.

**Comment by spock123** [comment]
Works fine here (Ubuntu 16.04)

**Comment by milichev** [comment]
The same issue! Was it ever fixed?

**Comment by devguysin** [comment]
Same issue here on Windows 10. How do I troubleshoot it?

**Comment by wangfei-1022** [comment]
hello. i have the same problem in Windows.did you solve this problem?thanks

**Comment by h22a** [comment]
Adding `"typeRoots": [ "./node_modules/@types" ]` to `tsconfig.json` should address the problem when running in Windows.

`tsconfig.json` after the change:

```
{
  "compileOnSave": false,
  "buildOnSave": false,
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "types": [
      "core-js",
      "node"
    ],
    "typeRoots": [ "./node_modules/@types" ]
  },
  "files": [],
  "exclude": [
    "node_modules",
    "dist"
  ]
}
```

Hope that helps.
@whyfind, @devguysin, @milichev

**Comment by sonicoder86** [comment]
Added it to the repository https://github.com/blacksonic/angular2-aot-webpack/commit/96b145afda0d0ccacb83968b7460abe823a728e6
