### ISSUE TITLE
Tree Shaking

### ISSUE THREAD

**Issue by spock123** [blacksonic/angular2-aot-webpack#11]
It is my impression that Webpack2 automatically can do tree shaking.

It just requires the Typescript compiler to output ES2015 modules instead of CommonJS (if you're using Typescript 2).

In your tsconfig:

```
{
  "compilerOptions": {
    "target": "es5",
     "module": "es2015",

```

Am I totally wrong on this?

**Comment by sonicoder86** [comment]
Yes it can be enabled by that, only pending issue is this https://github.com/mishoo/UglifyJS2/issues/1261

**Comment by spock123** [comment]
Ouch.. looks like I need rollup then.....

**Comment by sonicoder86** [comment]
Updated `tsconfig` to support tree-shaking, but it is not a game changer for now. fr details look at the Typescript tree-shaking repository

**Comment by mii9000** [comment]
@blacksonic I was testing out whether the bundles were being tree-shaked or not and for that I imported a class among others in a component but it seems all the exported class from that file is getting into the bundle.

`engine.ts`
```
export interface Engine {
  toString(): string;
}

export class V6Engine implements Engine {
  toString() {
    return 'V6';
  }
}

export class V8Engine implements Engine {
  toString() {
    return 'V8';
  }
}

export function getVersion() {
  return '1.0';
}
```

`hello-world.component.ts`
```
import { Component } from '@angular/core';
import { V8Engine } from './engine';

@Component({
  selector: 'hello-world-app',
  templateUrl: 'hello-world.template.html',
  styleUrls: ['hello-world.style.css']
})
export class HelloWorldComponent {

  ngAfterViewInit(){
      console.log(V8Engine.toString());
  }
}
```

So, according to the above example I would not expect to find `V6` string in the bundle but it seems its actually there in the bundle. Do we need to extend the webpack config to enable tree-shaking?

**Comment by BrainCrumbz** [comment]
Last news I remember were that tree-shaking without an additional Babel transpile step could not work. I think that was due to the way uglifyJs works, which makes hard to detect if some transpiled code is actually used or not. And as far as I remember such behaviour was not easy to change.
