### ISSUE TITLE
tsconfig.aot.json not found error

### ISSUE THREAD

**Issue by alexey-gorshkov** [blacksonic/angular2-aot-webpack#117]
ngc-watch.js 
line let ngcCommand = 'ngc -p ./tsconfig.aot.json';
![tsconfig-aot-json-notfound](https://cloud.githubusercontent.com/assets/15089615/24644618/c545721a-193e-11e7-945a-62404cbd0808.JPG)

**Comment by tonimitrevski** [comment]
Please update last commit and will works fine

**Comment by sonicoder86** [comment]
Now there is only a single `tsconfig.json`

**Comment by sonicoder86** [comment]
Fixed file name in command
