### ISSUE TITLE
Image loading problems

### ISSUE THREAD

**Issue by paulocoutinhox** [blacksonic/angular2-aot-webpack#13]
I have some projects that im porting to AOT, but i have the same problem with NG2 AOT: Loading images.

After searching a lot i created a simple project too, but now loading image (logo.png).
https://github.com/prsolucoes/angular2-webpack2-starter

The image is copied to "dist/assets/logo.png", but the IMG tag still reference to "images/logo.png" and not "assets/logo.png" 

:(

Can anyone help me?

**Comment by paulocoutinhox** [comment]
I have the same problem here:
https://github.com/prsolucoes/angular2-webpack2-starter/issues/1

**Comment by sonicoder86** [comment]
Images can be copied to a public directory, like the index.html and favicon.ico file.
Or define a loader for it in the Webpack config.

**Comment by paulocoutinhox** [comment]
I solve the problems in my repo...

**Comment by sonicoder86** [comment]
How did you solve the issue?

**Comment by SebastianStehle** [comment]
I am also interested how to integrate images in the webpack-aot-pipeline. It works well with html-loader.

**Comment by sonicoder86** [comment]
With `ngc` it is not possible to parse attributes like images for Webpack loaders.
It is only available when you use a Webpack plugin like `@ngtools/webpack` for AOT compilation.
