### ISSUE TITLE
NgcWebpackPlugin -> AoTPlugin?

### ISSUE THREAD

**Issue by qvazzler** [blacksonic/angular2-aot-webpack#14]
As title says, I think later versions of the packages require use of AoTPlugin now.

It would be a huge help to people to not have to figure this step out, since the documentation is a tad lacking atm. Thanks!

**Comment by sonicoder86** [comment]
Yes exactly it was renamed, can you submit a PR?

**Comment by qvazzler** [comment]
I made an attempt to use the project after upgrading, but it didn't work out of the box. I will try.

Meanwhile, I'm having trouble even using the now called aotplugin, despite my best efforts it still does not generate ngfactory files..

**Comment by qvazzler** [comment]
@blacksonic Pull request up #15. I'm also going to leverage this as a bug report to the fact that AotPlugin seems to not be generating ngfactories right now.

By the way, there are a lot of unmet dependency warnings, I'm going to just assume it's because we're on the bleeding edge.

**Comment by qvazzler** [comment]
https://github.com/angular/angular-cli/issues/2757

**Comment by sonicoder86** [comment]
Fixed with https://github.com/blacksonic/angular2-aot-webpack/pull/16
