### ISSUE TITLE
Cannot find name '_'

### ISSUE THREAD

**Issue by monvhh** [blacksonic/angular2-aot-webpack#17]
I am compiling the project, but there are errors as follows:
Cannot find name '_'.
Cannot find name '$'.

Sorry I knew little about how the aot compile and webpack...
I only know _ and $ is defined in the directory typings, lodash and jquery.

thanks

**Comment by monvhh** [comment]
I have typescript definition file  "./typings/index.d.ts". I don't know where to put it.

**Comment by sonicoder86** [comment]
you dont need typings just use @types/lodash and @types/jquery and atdd it to the types in tsconfig
