### ISSUE TITLE
Webpack dev-server with live-reload

### ISSUE THREAD

**Issue by arsenys** [blacksonic/angular2-aot-webpack#20]
Need to rerun npm task on every change. Is it possible to implement webpack-server to hot inject the changes?

**Comment by sonicoder86** [comment]
Added this functionality here https://github.com/blacksonic/angular2-aot-webpack/commit/b135d40ee4e1ed00169c2f00829792a898a43978

**Comment by bruno-preti-glb** [comment]
Is it me or it doesn't show the changes in a template after reloading?

**Comment by sonicoder86** [comment]
No, it is not working for me either.
Related issue: https://github.com/angular/angular-cli/issues/3084

**Comment by sonicoder86** [comment]
Added some live-reload goodness manually with `chokidar` to `npm start` : https://github.com/blacksonic/angular2-aot-webpack/commit/25f611dd727c10e562e1b47e12b60759fa2fb4a6

It works fine with `ngc`, but doesn't solve issue the with the Webpack plugin.

**Comment by paulocoutinhox** [comment]
Could you help e with a related issue?
https://www.youtube.com/watch?v=mQ0-C3uJpfg&feature=youtu.be

Thanks.

**Comment by sonicoder86** [comment]
Now it works also with the Webpack plugin and manual watching with ```ngc```.
