### ISSUE TITLE
Is it possible to compile a webpack bundle that's a mix of TypeScript and plain JavaScript?

### ISSUE THREAD

**Issue by msafi** [blacksonic/angular2-aot-webpack#21]
Hi,

[We're trying](https://github.com/text-mask/text-mask/issues/244) to figure out how to make [Text Mask](https://github.com/text-mask/text-mask) compatible with AoT compiled apps. The main challenge we're having is that the [TypeScript module](https://github.com/text-mask/text-mask/blob/master/angular2/src/angular2TextMask.ts#L4) imports a [JavaScript module](https://github.com/text-mask/text-mask/blob/master/core/src/createTextMaskInputElement.js).

Today we're using [this webpack configurations](https://github.com/text-mask/text-mask/blob/master/angular2/webpack.buildAngular2Integration.js), which as you can see it can work with a mix of JS (through `babel-loader`) and TS (through `awesome-typescript-loader`).

Is it possible to use ngTools (as shown in your example) to build Text Mask in a way that's compatible with AoT apps without having to convert the JS part of the library to TypeScript too?

Thanks a lot!

**Comment by sonicoder86** [comment]
I think it only accepts Typescript files, or Javascript files that have a metadata.json next to it.

**Comment by michaeljota** [comment]
According to this article [link](http://blog.mgechev.com/2016/08/14/ahead-of-time-compilation-angular-offline-precompilation/) it has to have a metadata.json next to it, as @blacksonic said. 

> ### AoT and third-party modules
> Alright, so the compiler needs metadata for the components in order to compile their templates. Lets suppose that in our application we use a thrid-party component library. How does the Angular AoT compiler knows the metadata of the components defined there if they are distributed as plain JavaScript? It oesn’t. In order to be able to compile ahead-of-time an application, referencing an external Angular library, the library needs to be distributed with the *.metadata.json produced by the compiler.
> For further reading on how to use the Angular compiler, you can take a look at the following link. For an example of how you can build your custom library in order to be AoT-ready, you can peek at the angular/mobile-toolkit.
