### ISSUE TITLE
Inline template require support

### ISSUE THREAD

**Issue by opiepj** [blacksonic/angular2-aot-webpack#27]
With Webpack will AOT be able to traverse require statements?

For example if you have:

```js
let template: string = require('./hello-world.template.html');
let myStyle: string = require('./hello-world.style.css');

@Component({
  selector: 'hello-world-app',
  template: template,
  styles: [myStyle]
})
export class HelloWorldComponent {}
```

This would be a nice feature as we might have `.scss` files or perhaps other html templates also maybe some script to determine which template to load for channel support, etc. 

Would AOT because to support this? I'm having trouble getting this to work.

**Comment by sonicoder86** [comment]
With require you can decide the type of the content and it is not supported for AOT for now.
You can preprocess files in .scss format then add styleUrls with .css extension.

**Comment by opiepj** [comment]
Sure, but then you couldn't do any HMR development when modifying SCSS. Maybe they will make a aot-loader soon.

**Comment by SebastianStehle** [comment]
It seems that the building takes place in the aot plugin. Therefore you cannot use preloaders and all the webpack magic.

Sucks :(

**Comment by sonicoder86** [comment]
It might work with sass loaders, haven't tried, but it might work with custom template loaders.
https://github.com/angular/angular-cli/tree/master/tests/e2e/assets/webpack/test-app

**Comment by sonicoder86** [comment]
@opiepj @SebastianStehle It is possible now with the Angular CLI Webpack plugin, moved it to a separate repository: https://github.com/blacksonic/angular2-aot-cli-webpack-plugin

**Comment by SebastianStehle** [comment]
@blacksonic I tried to combine this plugin with a convention loader https://github.com/AngularClass/angular2-conventions-loader. For me it does not work because the aot loader does not call webpack for the ts files.

**Comment by sonicoder86** [comment]
I think with the new version Decorators are inherited.

**Comment by sonicoder86** [comment]
But of course it is not AOT friendly, because this loader happens after AOT compilation.

**Comment by opiepj** [comment]
I can confirm that it works for me now :)
