### ISSUE TITLE
Issues loading non-aot version

### ISSUE THREAD

**Issue by paulocoutinhox** [blacksonic/angular2-aot-webpack#29]
Hi,

After try making non-ao version working i got this errors:
![screenshot 2016-11-08 22 40 13](https://cloud.githubusercontent.com/assets/395096/20123180/6a16a98e-a604-11e6-88cb-0a0737cabaa0.png)

Steps:
1. change src/index.html to load "<script src="bootstrap.bundle.js"></script>"
2. change package.json "ngc" command to "ngc -p ./tsconfig.json"
3. run "npm start-prod"

**Comment by sonicoder86** [comment]
Why would you change tsconfig to the non aot version?

**Comment by paulocoutinhox** [comment]
What is the process to generate the non-aot files?

**Comment by paulocoutinhox** [comment]
You dont need change nothing. Im running here:

> npm run webpack-prod
> npm run serve

Error:

![screenshot 2016-11-10 14 09 58](https://cloud.githubusercontent.com/assets/395096/20184300/61e9797a-a74f-11e6-8fbc-dda982b2dcb9.png)

**Comment by sonicoder86** [comment]
fixed it, `tsconfig.json` missed some setting for `awesome-typescript-loader`
