### ISSUE TITLE
ngfactory

### ISSUE THREAD

**Issue by daniele-zurico** [blacksonic/angular2-aot-webpack#35]
Is possible to generate the *.ngfactory.ts and *.shim.ts in a separate folder instead of the src?
I tried to add:
```
"angularCompilerOptions": {
    "genDir": "./ngfactory",
    "skipMetadataEmit" : true
  },
```

but it fail because"
```
ERROR in ./app/bootstrap.aot.ts
Module not found: Error: Can't resolve './modules/main.module.ngfactory' in '/Users/danielezurico/Desktop/angular2-aot-webpack-master/src/app'
 @ ./app/bootstrap.aot.ts 2:0-70

ERROR in [default] /Users/danielezurico/Desktop/angular2-aot-webpack-master/src/app/bootstrap.aot.ts:2:36 
Cannot find module './modules/main.module.ngfactory'.
```

**Comment by sonicoder86** [comment]
You can modify it with `"outDir": "./ngfactory"` and then you have to modify the bootstrap file also.

**Comment by daniele-zurico** [comment]
Auch.. You right I didn't change the import in the aot file.
Question is correct to have something like that:

```
    "noFallthroughCasesInSwitch": true,
    "outDir": "./ngfactory",
```

and

```
  "angularCompilerOptions": {
    "genDir": "./aot",
    "skipMetadataEmit" : true
  },
```

I need two different directory? is better? I can merge them in the same directory? I don't understand the meaning

**Comment by sonicoder86** [comment]
`outDir` stands for the `ngfactory` files, `genDir` stands for the transpiled Javascript files.

**Comment by daniele-zurico** [comment]
awesome tnx
