### ISSUE TITLE
how I can add sass support?

### ISSUE THREAD

**Issue by daniele-zurico** [blacksonic/angular2-aot-webpack#36]
I'm trying that one but it break:
```
loaders: [{
  test: /\.scss$/,
  loader: ExtractTextPlugin.extract(
    "style",
    "css!sass")
 }]
},
```
I added a repro:

[repo](https://github.com/daniele-zurico/webpack-aot)

**Comment by sonicoder86** [comment]
Found this example project here https://github.com/angular/angular-cli/tree/master/tests/e2e/assets/webpack/test-app

**Comment by daniele-zurico** [comment]
Oh yes I forgot to tell you. Sorry. You can look on my GitHub it's exactly the same ;)

**Comment by sonicoder86** [comment]
Does it recompile when you change the the sass file?
https://github.com/angular/angular-cli/issues/3084

**Comment by daniele-zurico** [comment]
I was just interested about the AOT compilation so not live watching, it's a long process when the application is big so the live reloading is pointless
