### ISSUE TITLE
Why are compiled files checked in to source control? 

### ISSUE THREAD

**Issue by pdavin-zz** [blacksonic/angular2-aot-webpack#42]
This example AoT project is helpful, but the ngfactory.ts files and .js compiled files are checked in to the git repo. This wouldn't be done normally I believe, and it makes the sample harder to follow. I can't easily determine which files are generated and which are original source. 

For example, what is /ngfactory/main.js for? This seems to be duplicative with /ngfactory/modules/main.module.js, and I can't find which source Typescript file the main.js corresponds to. Further, when I delete the ngfactory folder and regenerate with 'npm run ngc', no ngfactory/main.* files are created.

**Comment by sonicoder86** [comment]
Originally I included them to show what the generated files will look like.

The ```ngfactory/main.js``` is a leftover before renaming it to ```main.module.ts```.
If removing the ```ngfactory``` directory clarifies a lot, then it is ok to remove. It is also a best practice not to put these files into source control.

**Comment by pdavin-zz** [comment]
Ok, got it. So I guess this is "by design". However it's still confusing to me that the "ngfactory" folder is not used for the *.ngfactory.ts files. The ngfactory folder is being used as the compiler outDir, which is more of a bin dir. The ngc ngfactory files are going into src (because no genDir is set in angularCompilerOptions).  

What I'm hoping to figure out is how to setup an app with the ngfactory files in a different gen dir (and still be able to compile the AoT bootstrapper - bootstrap.aot.ts - from src. This is surprisingly difficult.

**Comment by sonicoder86** [comment]
Yes, ngfactory is misleading indeed, should be renamed.

haven't tried it with different ```genDir```, but it would also clarify a lot.

**Comment by sonicoder86** [comment]
@pdavin Moved ngfactory directory to tmp, because it is not used by the application at all.

**Comment by sonicoder86** [comment]
Removed ngfactory files also, because they have hidden a bug also, now everything works.
