### ISSUE TITLE
bootstrap in index.html

### ISSUE THREAD

**Issue by jk21** [blacksonic/angular2-aot-webpack#47]
Hello,

it is possible to not have to change the index.html if you want to build the page or to develop?

now i always have to switch between bootstrap.bundle.js and bootstrap.aot.bundle.js

**Comment by jk21** [comment]
Hello,

i think it could be possible with the HtmlWebpackPlugin and different env-values.
But i cant make the Plugin work.
Could you mb add the plugin so it works with different env values?

`const ENV = process.env.NODE_ENV = process.env.ENV = 'production';`

like in the angular2-webpack-starter project

**Comment by sonicoder86** [comment]
@jk21 Moved both AOT and JIT compilation result to same output file, no more need to manually uncomment.
