### ISSUE TITLE
What does "exclude" do in tsconfig.json?

### ISSUE THREAD

**Issue by gbaldeck** [blacksonic/angular2-aot-webpack#54]
tsconfig.json contains this key:

"exclude": [
    "node_modules",
    "dist",
    "**/*.ngfactory.ts",
    "**/*.shim.ts",
    "src/app/main*.ts",
    "src/app/polyfill.ts"
  ],

Why do we want to exclude the last 4 entries in that list? Don't we want Typescript to compile those to Javascript?

**Comment by sonicoder86** [comment]
It only excludes files from AOT compilation. Transpilation is not affected from Typescript to Javascript.
Compiling those files can cause errors or warnings.
