### ISSUE TITLE
Tree-shaking with Typescript >2.0

### ISSUE THREAD

**Issue by mii9000** [blacksonic/angular2-aot-webpack#57]
@blacksonic I was testing out whether the bundles were being tree-shaked or not and for that I imported a class among others in a component but it seems all the exported class from that file is getting into the bundle.

`engine.ts`
```
export interface Engine {
  toString(): string;
}

export class V6Engine implements Engine {
  toString() {
    return 'V6';
  }
}

export class V8Engine implements Engine {
  toString() {
    return 'V8';
  }
}

export function getVersion() {
  return '1.0';
}
```

`hello-world.component.ts`
```
import { Component } from '@angular/core';
import { V8Engine } from './engine';

@Component({
  selector: 'hello-world-app',
  templateUrl: 'hello-world.template.html',
  styleUrls: ['hello-world.style.css']
})
export class HelloWorldComponent {

  ngAfterViewInit(){
      console.log(V8Engine.toString());
  }
}
```

So, according to the above example I would not expect to find `V6` string in the bundle but it seems its actually there in the bundle. Do we need to extend the webpack config to enable tree-shaking?

**Comment by sonicoder86** [comment]
Here is the exact explanation for this behavior https://github.com/webpack/webpack/issues/2899

**Comment by sonicoder86** [comment]
Currently it is only possible for classes with Rollup in an easy way.

**Comment by mii9000** [comment]
@blacksonic Thanks for your reply really helpful. So, are you suggesting to ditch webpack and use Rollup for a build with tree-shaking?

**Comment by sonicoder86** [comment]
I wouldn't ditch Webpack, it does a lot of things that Rollup doesn't through loaders and plugins and sooner or later they will solve it.
For the sole purpose of tree-shaking i wouldn't.
