### ISSUE TITLE
PreLoaders for templates

### ISSUE THREAD

**Issue by unsafecode** [blacksonic/angular2-aot-webpack#6]
What about running a pre loader for templates before ngc? Can ngc be part of Webpack pipeline, maybe as a plug in?

**Comment by sonicoder86** [comment]
With awesome-typescript-loader we can add template loading. Ngc as part of Webpack loading i have no idea how to solve it.

**Comment by unsafecode** [comment]
@blacksonic Looks like angular/compiler-cli APIs are not fully exposed, so it I'm afraid it'll take some time

**Comment by MehdiZonjy** [comment]
The angular/compiler-cli seems to be able to handle "templateUrl" when used inside component declaration, so you don't need to inline your templates inside your component file.
Just make sure you are using bootstrap.aot.bundle.js and those separate html template files won't be requested by the browser. I just tested it and it seems to be working properly

**Comment by sonicoder86** [comment]
@unsafecode @MehdiZonjy removed inline template from component, now using templateUrl

**Comment by sonicoder86** [comment]
https://github.com/blacksonic/angular2-aot-webpack/commit/9bd19bde31f15ba20e9608a8ea46e41ea2612857

**Comment by unsafecode** [comment]
@blacksonic Do you know whether the updated webpack loader config you provided may also support, for instance, pre-loading a template and applying a string-replace-loader this way?

**Comment by sonicoder86** [comment]
If you add it to html files it should work.
What it does is to inline the html from the templateUrl and replace it to a require statement, then Webpack takes over at compiling.
The more problematic is the aot part, i dont know how to hook up there.

**Comment by unsafecode** [comment]
@blacksonic Exactly, I was thinking about AoT

**Comment by jpguevara** [comment]
Hi @blacksonic , did you manage to solve this issue?

**Comment by sonicoder86** [comment]
Haven't worked with it in connection with `ngc`, but it works with Webpack loaders in [my separate repository](https://github.com/blacksonic/angular2-aot-cli-webpack-plugin)
