### ISSUE TITLE
AOT compilation requires component name.

### ISSUE THREAD

**Issue by dzmitrypaulouski** [blacksonic/angular2-aot-webpack#65]
Hello,

I have an issue with AOT compilation. When I run a build task it asks me for some new component name. It will be an issue for CI. Here is an example:

![image](https://cloud.githubusercontent.com/assets/10211927/22685061/e5afb4b0-ed2f-11e6-8531-5ecc2a0acb5d.png)

My tsconfig.json file:

```
{
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [ "es6", "dom" ],
    "mapRoot": "./",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "./node_modules/@types"
    ],
    "types": [
      "node"
    ],
    "noUnusedLocals": true,
    "pretty": true,
    "removeComments": true
  },
  "angularCompilerOptions": {
    "genDir": ".",
    "entryModule": "src/app/app.module#AppModule"
  }
}
```

Could you please advise how to avoid this name input?`

**Comment by blacksonic** [comment]
Seems like Angular issue.

**Comment by sonicoder86** [comment]
What happens if you type in the name? @dzmitrypaulouski
