### ISSUE TITLE
How to AoT compile and webpack everything without webpack-dev-server?

### ISSUE THREAD

**Issue by papaiatis** [blacksonic/angular2-aot-webpack#86]
Hi!

I'm building a full stack webapp with NodeJS on the backend. Express serves the HTTP requests.
I'm trying to create a production build process that uses ngc and webpack. 
As I'm using my own Express app I don't need webpack-dev-server.
How should I configure the "npm run aot" script to tell webpack to create a bundle for me that is actually working?

Thanks!

**Comment by sonicoder86** [comment]
Just run it with `webpack` and serve the static files from the output directory.

**Comment by papaiatis** [comment]
I've ended up using @ngtools/webpack. It does exactly what I want.
